### ISSUE TITLE
issue with .net core 3.1

### ISSUE THREAD

**Issue by ameena1976** [thiagoloureiro/APIGatewayOcelot#1]
I tried to use the APIGateway (Ocelot) with .net core 3.1.
But it does not work as expected. API routing is not working and didn't find any error.

**Comment by sonuame** [comment]
can you paste one of your route ?
and make sure the route property is "Route" not "ReRoute"

**Comment by ameena1976** [comment]
Hi Sunit,

I have used the below code snippet in configuration.json.

{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/user",
      "DownstreamScheme": "http",
      // "DownstreamHost": "localhost",
      // "DownstreamPort": 9001,
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 62187
        }
      ],
      "UpstreamPathTemplate": "/user",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ]
}

My User api is running fine on port-62187.

In the Program.cs, i have written the below simple code.

   public static void Main(string[] args)
        {
            new WebHostBuilder()
               .UseKestrel()
               .UseContentRoot(Directory.GetCurrentDirectory())
               .ConfigureAppConfiguration((hostingContext, config) =>
               {
                   config
                       .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                       .AddJsonFile("configuration.json")
                       .AddEnvironmentVariables();
               })
               .ConfigureServices(s => {
                   s.AddOcelot();
               })
               .ConfigureLogging((hostingContext, logging) =>
               {
                   //add your logging
               })
               .UseIISIntegration()
               .Configure(app =>
               {
                   app.UseOcelot().Wait();
               })
               .Build()
               .Run();
        }

But when i am trying to run the api gateway url, it is only showing and nothing is displaying.


But the same code is working fine with .net core 2..2

Regards,
Ameena VErma

**Comment by sonuame** [comment]
Code looks fine. But if if the gateway is still not working that means upstream route is not matching up
2 things can you double check
1) if the path for configuration file is correct
2) your upstream url ends with /user? or there is more to the url like /user/find, /user?id=?

because if it is so then you need to add upstream url as /user/{everything}

enable debug log in the configuration as 
`"Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Information"
    }
  }`

**Comment by sonuame** [comment]
this is what i have in mine
Ignore Consul part

![image](https://user-images.githubusercontent.com/658382/83507677-7e806b00-a4e6-11ea-929a-1c3b4df64ae5.png)

**Comment by ameena1976** [comment]
[Microservice.zip](https://github.com/thiagoloureiro/APIGatewayOcelot/files/4716359/Microservice.zip)

i have used apigateway2 using .net core 2.2 and created apigateway3 with .net core 3.1.
but no success with .net core 3.1

**Comment by sonuame** [comment]
OK, I checked your code and its running successfully without any major change.
problem is, you are running gateway as an IISExpress app which is not possible because ocelot works as EndpointRouting app which was not the case in 2.2

goto properties and delete the launch profile for IIS. it shud run as console

![image](https://user-images.githubusercontent.com/658382/83509048-71fd1200-a4e8-11ea-8de0-6049d21e776e.png)

**Comment by sonuame** [comment]
There you go..!!

[Microservice.zip](https://github.com/thiagoloureiro/APIGatewayOcelot/files/4716461/Microservice.zip)

**Comment by ameena1976** [comment]
Thanks Sunil for your help.

It is working now.

Thanks once again.

regards,
Ameena VErma

**Comment by sonuame** [comment]
> Thanks Sunil for your help.
> 
> It is working now.
> 
> Thanks once again.
> 
> regards,
> Ameena VErma

No worries, Glad I could help.

**Comment by thiagoloureiro** [comment]
I've updated the repo to 3.1, should solve the issues as well
